### ISSUE TITLE
Chore(tests): Change transaction log checking

### ISSUE THREAD

**Issue by adapap** [StevensSEC/pokemonbattlelib#146]
Every time a new transaction is added or modified, many tests need to be updated with the new information. This usually is derived from the order or number of transactions occurring in a given battle. Since it's not reasonable to limit the number of transactions that occur while expanding the library, I suggest that we take the approach of writing tests that assert that certain transactions _do_ or _do not_ occur.

For example, in testing fainting logic, we are not concerned with the specific damage that occurred, friendship lost, swapping Pokemon, exp gained, etc. We only want to test: does some transaction contain "X fainted."

This will simplify some tests as well and avoid redundancy.

**Comment by dyc3** [comment]
@adapap does #164 fix this?

**Comment by adapap** [comment]
Yes, it directly addresses the issue IMO.
