### ISSUE TITLE
Validate Pokemon for battle

### ISSUE THREAD

**Issue by adapap** [StevensSEC/pokemonbattlelib#147]
Possible duplicate of #34.

Pokemon should be validated before a battle begins. Some of the battle codes assumes that a Pokemon has moves, so we want to avoid nil references if no moves are provided.

See [requirements for Pokemon](https://github.com/StevensSEC/pokemonbattlelib/wiki/Requirements#pokemon).

**Comment by dyc3** [comment]
I think we should put this validation in `AddPokemon`, when adding pokemon to the party. Seems like the most logical place.

**Comment by dyc3** [comment]
Would like to see something like this in the implementation:

```go
var ErrorValidationMissingMoves = errors.New("Pokemon needs at least 1 move.")

func (p *Pokemon) Validate() error {
	hasMoves := false
	for _, m := range p.Moves {
		if m != nil {
			hasMoves = true
			break
		}
	}
	if !hasMoves {
		return ErrorValidationMissingMoves
	}

	// ...

	return nil
}
```
