### ISSUE TITLE
Simplify `HaveTransaction` parameters?

### ISSUE THREAD

**Issue by adapap** [StevensSEC/pokemonbattlelib#186]
While most of the time it is helpful to explicitly state all of the fields of the transactions expected, sometimes doing so leads to undecipherable error messages or extra fields not needed for the specific test. Examples are including `party` and `partySlot` which default to 0 already, or the error message from the transactions not matching.

It might make more sense to have something like this:
```
Expect(transactions).To(HaveTransaction(DamageTransaction))
Expect(poke.CurrentHP).To(BeEquivalentTo(15))
```

**Comment by dyc3** [comment]
If the error messages from the matcher are hard to decipher, then that should be fixed.

It would probably be nice to be able to display a nice colored diff of the matching fields of the transaction.
