### ISSUE TITLE
History of last move used by a Pokemon

### ISSUE THREAD

**Issue by adapap** [StevensSEC/pokemonbattlelib#192]
3 cases where this is needed, there are definitely more:
 [Choice Scarf/Band/Specs](https://bulbapedia.bulbagarden.net/wiki/Choice_Scarf) - limits holder to one move
[Spite](https://bulbapedia.bulbagarden.net/wiki/Spite_(move)) - decreases PP of last used move on target
[Grudge](https://bulbapedia.bulbagarden.net/wiki/Grudge_(move)) - if a move causes user to faint, fainting move loses all PP

**Comment by dyc3** [comment]
Depending on the implementation, this could be combined with #135
