### ISSUE TITLE
Split up battle rounds into a sequence

### ISSUE THREAD

**Issue by adapap** [StevensSEC/pokemonbattlelib#196]
Many effects in a battle happen either before or after turns are processed, so in order to make it easier to track the order of events in battle, I suggest we have `battle.SimulateRound` include a `battle.PreRound` and `battle.PostRound` call. Alternatively, this can be done for each turn instead of round. This is an important issue as it will affect how we set meta tags in a battle before they are used, and ensure order of events after all turns are processed.

**Comment by dyc3** [comment]
Sure, but I think that they should be private methods called by SimulateRound
