### ISSUE TITLE
Add the HoldItem type

### ISSUE THREAD

**Issue by adapap** [StevensSEC/pokemonbattlelib#20]
Held items change the way that a Pokemon battle functions drastically. Each hold item belongs to a class (such as Stat Modifier, Medicine, Berries, or other effects. Representing items will be challenging, as there are many different types of items that produce different effects. Also, we must determine if we want to include all possible items or only those which have an affect on the battle itself.

This issue should be incremental, with the data representation being the first and simplest layer.

**Comment by dyc3** [comment]
Removed from Working battles milestone because its technically not required for bare minimum working battles.
