### ISSUE TITLE
Check if Pokemon is holding an item

### ISSUE THREAD

**Issue by adapap** [StevensSEC/pokemonbattlelib#227]
Syntactic sugar for this pattern:
`if p.HeldItem != nil && p.HeldItem.ID == itemID`

I'm thinking one of these solutions:
`p.GetHeldItem() int` // returns item ID, or -1
`p.HasHeldItem(...id int) bool` // returns true if Pokemon is holding any of the given items

**Comment by dyc3** [comment]
We should just reference items by their ID, and look up their data when needed

**Comment by adapap** [comment]
I don't think this solves the issue, because we would still need to check for the presence of an item e.g. `p.HeldItem != 0` or `-1`, whatever. `GetItem(id)` panics if an item is not found.
