### ISSUE TITLE
Items still missing consumable flag

### ISSUE THREAD

**Issue by adapap** [StevensSEC/pokemonbattlelib#281]
Not sure if this is the only case, but Focus Sash is missing a `FlagConsumable` which is causing errors in my testing of #211 

Related: #204

**Comment by dyc3** [comment]
What item category is it in?

**Comment by adapap** [comment]
`ItemCategoryHeldItems` I think. https://veekun.com/dex/items/misc/focus%20sash

**Comment by dyc3** [comment]
It looks like not all the items in that category get consumed when used. I'm thinking that we should just modify the CSV with that flag rather than hard code it in the code generation.

**Comment by adapap** [comment]
Possibly, I don't know if there is a better way. Also applies to these items:
- Mental Herb
