### ISSUE TITLE
Validate teams at beginning of battle

### ISSUE THREAD

**Issue by dyc3** [StevensSEC/pokemonbattlelib#34]
Relevant code: https://github.com/StevensSEC/pokemonbattlelib/blob/07c4cf0a2732d5aafef2b9bc722b7e4e08804ae6/battle.go#L53-L57

**Comment by adapap** [comment]
Responding to #57, teams should be validated in `battle.Start`. The check should be that there exists (at the moment) exactly two teams with 1 or more agents on each team.

https://github.com/StevensSEC/pokemonbattlelib/blob/5d0270a39720dd9784a43f33ee9c7e1573ab71db/battle.go#L64-L73

**Comment by dyc3** [comment]
Unassigning due to inactivity.
