### ISSUE TITLE
Implement SwitchTurn type and add case to SimulateRound()

### ISSUE THREAD

**Issue by carpenterd777** [StevensSEC/pokemonbattlelib#36]
This will represent a turn where a Trainer changes their active Pokemon (the one currently battling) to a Pokemon in their party that has not yet fainted.

See: https://github.com/StevensSEC/pokemonbattlelib/wiki/Requirements#pokemon-switching-out

Switching Pokemon always takes precedence to any `FightTurn`s that may occur, essentially placing it in the highest priority bracket (higher than any move would have). (The exception is the move Pursuit, but this has not been implemented yet. It should be kept in mind while designing the type though.)

- [x] Switching Pokemon passes the turn
- [x] Switching Pokemon takes place before any `FightTurn`s
- [x] A Trainer cannot switch to a fainted Pokemon
- [x] A Trainer cannot switch to the already active Pokemon
- [x] Add case to `SimulateRound()`

**Comment by dyc3** [comment]
Unassigning due to inactivity.
