### ISSUE TITLE
Items: Berries

### ISSUE THREAD

**Issue by adapap** [StevensSEC/pokemonbattlelib#47]
Add functionality for effects of berries in battle. Each berry is consumed upon usage and typically affects 1 or more stat values.

See: https://veekun.com/dex/items/berries

### In-a-pinch
Num | Item | Effect
-- | -- | --
57 | Apicot Berry | Held: Consumed at 1/4 max HP to boost Special Defense.
62 | Custap Berry | Held: Consumed at 1/4 max HP when using a move to go first.
54 | Ganlon Berry | Held: Consumed at 1/4 max HP to boost Defense.
58 | Lansat Berry | Held: Consumed at 1/4 max HP to boost critical hit ratio by two stages.
53 | Liechi Berry | Held: Consumed at 1/4 max HP to boost Attack.
61 | Micle Berry | Held: Consumed at 1/4 max HP to boost accuracy of next move by 20%. (Gen IV: Perfect accuracy)
56 | Petaya Berry | Held: Consumed at 1/4 max HP to boost Special Attack.
55 | Salac Berry | Held: Consumed at 1/4 max HP to boost Speed.
59 | Starf Berry | Held: Consumed at 1/4 max HP to boost a random stat by two stages.

### Medicine
Num | Item | Effect
-- | -- | --
5 | Aspear Berry | Held: Consumed when frozen to cure frozen.
1 | Cheri Berry | Held: Consumed when paralyzed to cure paralysis.
2 | Chesto Berry | Held: Consumed when asleep to cure sleep.
6 | Leppa Berry | Held: Consumed when a move runs out of PP to restore its PP by 10.
9 | Lum Berry | Held: Consumed to cure any status condition or confusion.
7 | Oran Berry | Held: Consumed at 1/2 max HP to recover 10 HP.
3 | Pecha Berry | Held: Consumed when poisoned to cure poison.
8 | Persim Berry | Held: Consumed when confused to cure confusion.
4 | Rawst Berry | Held: Consumed when burned to cure a burn.
10 | Sitrus Berry | Held: Consumed at 1/2 max HP to recover 1/4 max HP.

### Other
Num | Item | Effect
-- | -- | --
60 | Enigma Berry | Held: Consumed when struck by a super-effective attack to restore 1/4 max HP.
63 | Jaboca Berry | Held: Consumed to deal 1/8 attacker's max HP when holder is struck by a physical attack.
? | Kee Berry | Held: When the holder is hit by a physical move, increases its Defense by one stage.
? | Maranga Berry | Held: When the holder is hit by a special move, increases its Special Defense by one stage.
64 | Rowap Berry | Held: Consumed to deal 1/8 attacker's max HP when holder is struck by a special attack.

### Picky Healing
Num | Item | Effect
-- | -- | --
14 | Aguav Berry | Held: Consumed at 1/2 max HP to restore 1/8 max HP. Confuses Pokémon that dislike bitter flavor.
11 | Figy Berry | Held: Consumed at 1/2 max HP to restore 1/8 max HP. Confuses Pokémon that dislike spicy flavor.
15 | Iapapa Berry | Held: Consumed at 1/2 max HP to restore 1/8 max HP. Confuses Pokémon that dislike sour flavor.
13 | Mago Berry | Held: Consumed at 1/2 max HP to restore 1/8 max HP. Confuses Pokémon that dislike sweet flavor.
12 | Wiki Berry | Held: Consumed at 1/2 max HP to restore 1/8 max HP. Confuses Pokémon that dislike dry flavor.

### Type protection
Num | Item | Effect
-- | -- | --
51 | Babiri Berry | Held: Consumed when struck by a super-effective Steel-type attack to halve the damage.
47 | Charti Berry | Held: Consumed when struck by a super-effective Rock-type attack to halve the damage.
52 | Chilan Berry | Held: Consumed when struck by a Normal-type attack to halve the damage.
41 | Chople Berry | Held: Consumed when struck by a super-effective Fighting-type attack to halve the damage.
44 | Coba Berry | Held: Consumed when struck by a super-effective Flying-type attack to halve the damage.
50 | Colbur Berry | Held: Consumed when struck by a super-effective Dark-type attack to halve the damage.
49 | Haban Berry | Held: Consumed when struck by a super-effective Dragon-type attack to halve the damage.
48 | Kasib Berry | Held: Consumed when struck by a super-effective Ghost-type attack to halve the damage.
42 | Kebia Berry | Held: Consumed when struck by a super-effective Poison-type attack to halve the damage.
36 | Occa Berry | Held: Consumed when struck by a super-effective Fire-type attack to halve the damage.
37 | Passho Berry | Held: Consumed when struck by a super-effective Water-type attack to halve the damage.
45 | Payapa Berry | Held: Consumed when struck by a super-effective Psychic-type attack to halve the damage.
39 | Rindo Berry | Held: Consumed when struck by a super-effective Grass-type attack to halve the damage.
43 | Shuca Berry | Held: Consumed when struck by a super-effective Ground-type attack to halve the damage.
46 | Tanga Berry | Held: Consumed when struck by a super-effective Bug-type attack to halve the damage.
38 | Wacan Berry | Held: Consumed when struck by a super-effective Electric-type attack to halve the damage.
40 | Yache Berry | Held: Consumed when struck by a super-effective Ice-type attack to halve the damage.

**Comment by dyc3** [comment]
I'm going to split this issue up into smaller ones, and close this one.
