### ISSUE TITLE
Tests that check std output pass when they shouldn't

### ISSUE THREAD

**Issue by dyc3** [StevensSEC/pokemonbattlelib#49]
## Current Behavior
Some of the current tests that check the std output are not actually checking it.

**To Reproduce**
If you take the `TestBattleOneRound` and change the expected output, the test will still pass.

**Evironment:**
 - OS: Ubuntu 20.04

**Additional context**

**Comment by adapap** [comment]
This is because output is only checked when writing test cases with the name `ExampleXXX`. See https://golang.org/pkg/testing/#hdr-Examples.
