### ISSUE TITLE
Pokemon Party building tools

### ISSUE THREAD

**Issue by dyc3** [StevensSEC/pokemonbattlelib#61]
**Is your feature request related to a problem? Please describe.**
Users are going to want to build parties quickly, and we're going to want it to write tests.

Currently, the steps to building a party are:
1. Create the party
2. Create the pokemon
3. Set the pokemon moves
4. Set the pokemon stats
5. Set the pokemon's current hp to the max hp
6. Repeat 2-5 up to 5 more times
7. Add all the pokemon to the party

This kinda sucks, especially because of step 5.

**Describe the solution you'd like**

There should be some way to generate pokemon with correct stats based on the national dex number and level

The process should look more like:
1. Create the party
2. Generate a pokemon
3. Set the pokemon moves
4. Repeat 2-3 up to 5 more times
5. Add all the pokemon to the party

However, it needs to still be possible to hand craft pokemon if needed. This would be just a convenience tool.

**Describe alternatives you've considered**

**Additional context**

**Comment by adapap** [comment]
(nit) Can step 1 and step 5 be one step? For example, creating a party takes Pokemon as parameters, but a separate party add/remove function exists.

**Comment by dyc3** [comment]
That would also be useful to have.
