### ISSUE TITLE
Add the Battle type

### ISSUE THREAD

**Issue by dyc3** [StevensSEC/pokemonbattlelib#7]
We need a way to track the current state of a Pokemon battle.

It's not necessary for the first iteration of this type to be perfect. We can change it later if needed.

### Tasks

- [ ] Define the contents of `type Battle struct` that necessary for a Pokemon battle.

**Comment by A-very-Cunning-ham** [comment]
Is this closed by #13?

**Comment by dyc3** [comment]
Partially, but not entirely.

**Comment by dyc3** [comment]
Things like weather, or other battlefield effects need to be added.

See this document: https://github.com/StevensSEC/pokemonbattlelib/wiki/Requirements
