### ISSUE TITLE
go generate does not regenerate pokedex_GEN.go

### ISSUE THREAD

**Issue by dyc3** [StevensSEC/pokemonbattlelib#77]
## Current Behavior
go generate does not regenerate pokedex_GEN.go

**To Reproduce**
1. delete `pokedex_GEN.go`
2. run `go generate`
3. See that `pokedex_GEN.go` is not created.

## Expected Behavior
`go generate` should regenerate `pokedex_GEN.go`, even if `pokedex_GEN.go` is not already present.

**Additional context**
Seems like `pokedex.go` was removed. `pokedex.go` should be recreated with 
```
//go:generate go run data/gen.go
```
_Note that there is no spaces in `//go:generate`_

**Comment by adapap** [comment]
Fixed in #42
