### ISSUE TITLE
Consolidate numeric types

### ISSUE THREAD

**Issue by adapap** [StevensSEC/pokemonbattlelib#78]
We currently use a mix of `int`, `uint`, `uint8`, `uint16`, and `float64` throughout the library. I think the performance benefits do not outweigh the confusion from mixing these types together, so I suggest that we pick 1 integer type and one floating point type.

**Comment by dyc3** [comment]
I would like to have benchmarks in place so we can actually measure the impact of this. PR #128 contains a pretty bare minimum benchmark.

**Comment by dyc3** [comment]
I'm starting to encounter lots of rounding errors that break lots of tests when modifying the damage calculation because we're casting stuff to `float64`.
